name: Build

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      push:
        required: false
        type: boolean
        default: true
    secrets:
      username:
        required: true
      password:
        required: true
      build-secrets:
        required: false

jobs:
  container-image:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Log into ECR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ inputs.registry }}/${{ inputs.repository }}
          tags: type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: ${{ secrets.build-secrets }}
