name: Deploy

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      cluster:
        required: true
        type: string
      namespace:
        required: true
        type: string
      krane-dir:
        required: true
        type: string
      version:
        required: false
        type: string
      aws-region:
        required: false
        type: string
        default: us-east-1
      kubectl-version:
        required: false
        type: string
        default: v1.30.5
      approval:
        required: false
        type: boolean
        default: false
      approval-timeout:
        required: false
        type: number
        default: 60
      approvers:
        required: false
        type: string
        default: Admins
      minimum-approvals:
        required: false
        type: number
        default: 1
      approval-initiator:
        required: false
        type: boolean
        default: true
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      approval-app-id:
        required: false
      approval-private-key:
        required: false

jobs:
  approval:
    if: inputs.approval
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Can't be more, because generated token expire after this time.
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.approval-app-id }}
          private_key: ${{ secrets.approval-private-key }}

      - name: Pending approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: ${{ inputs.approvers }}
          minimum-approvals: ${{ fromJSON(inputs.minimum-approvals) }}
          timeout-minutes: ${{ fromJSON(inputs.approval-timeout) }} # Can't be more than 60 minutes, because generated token expire after this time.
          issue-title: "Deployment Approval Required - ${{ inputs.cluster }}"
          issue-body: |
            A new deployment to ${{ inputs.cluster }} environment requires your approval.

            If no approval is given within ${{ inputs.approval-timeout }} minutes, the workflow will timeout and need to be re-run.

            Please review and approve or reject this deployment.
          exclude-workflow-initiator-as-approver: ${{ inputs.approval-initiator }}

  deploy:
    needs: [approval]
    if: always() && (needs.approval.result == 'success' || needs.approval.result == 'skipped')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: ruby:3.1-alpine3.19
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Install AWS CLI
        run: apk add aws-cli

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
        
      - name: Install kubectl
        uses: Azure/setup-kubectl@v3
        with:
          version: ${{ inputs.kubectl-version }}

      - name: Configure kubectl
        run: aws eks update-kubeconfig --name ${{ inputs.cluster }} --alias ${{ inputs.cluster }}

      - name: Install dependencies for Krane
        run: apk add build-base

      - name: Install Krane
        run: gem install krane

      - name: Extract Docker metadata
        if: inputs.version == ''
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ inputs.registry }}/${{ inputs.repository }}
          tags: type=sha

      - name: Deploy
        run: |
          krane render --filenames ${{ inputs.krane-dir }} --bindings=version=${{ inputs.version || steps.meta.outputs.version }} |
          krane deploy ${{ inputs.namespace }} ${{ inputs.cluster }} -f -
