name: Create Tag and Release on PR Merge

on:
  push:
    branches:
      - main

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_time=$(date -u +"%Y-%m-%d.%H%M")
          tag_name="v$current_time"
          git tag $tag_name
          git push origin $tag_name
          echo "tag_name=$tag_name" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ env.tag_name }}
          tag: ${{ env.tag_name }}
