name: Tag

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Log into ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ inputs.registry }}/${{ inputs.repository }}
          tags: type=sha

      - name: Add the release as a tag to the Docker image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ inputs.registry }}/${{ inputs.repository }}:${{ steps.meta.outputs.version }}
          dst: ${{ inputs.registry }}/${{ inputs.repository }}:${{ github.ref_name }}
